export const slider = [
  {
    name: "DANCE1",
    src: "src/img/WEB/SLIDER/DANCE1.jpg",
  },
  {
    name: "EXPRIMIDOR",
    src: "src/img/WEB/SLIDER/EXPRIMIDOR1.jpg",
  },
  {
    name: "EXPRIMIDOR",
    src: "src/img/WEB/SLIDER/EXPRIMIDOR2.jpg",
  },
  {
    name: "QUIJOTADAS",
    src: "src/img/WEB/SLIDER/QUIJOTADAS1.jpg",
  },
  {
    name: "QUIJOTADAS",
    src: "src/img/WEB/SLIDER/QUIJOTADAS2.jpg",
  },
  {
    name: "TOSTADOR",
    src: "src/img/WEB/SLIDER/TOSTADOR.jpg",
  },
];

export const filters = [
  {
    category: "todo",
    images: [
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE1.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE2.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "GARGHOLA",
        src: "src/img/WEB/GARGHOLA/GARGHOLA.jpg",
        alt: "GARGHOLA",
        filts: "PACKAGING | LETTERING | ILUSTRACIÓN",
      },
      {
        name: "MOTO",
        src: "src/img/WEB/MOTO/MOTO_1.jpg",
        alt: "MOTO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "MOTO",
        src: "src/img/WEB/MOTO/MOTO_2.jpg",
        alt: "MOTO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "UBICACIÓN",
        src: "src/img/WEB/UBICACION/UBICACION.jpg",
        alt: "UBICACIÓN",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "VINAGRE DE LA ALMUDENA",
        src: "src/img/WEB/ALMUDENA.jpg",
        alt: "VINAGRE-DE-LA-ALMUDENA",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_1..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_2..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_3..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_4..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_5..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "WRITERS",
        src: "src/img/WEB/RETRATOS/BRADBURY.jpg",
        alt: "WRITERS",
        filts: "RETRATOS",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_1.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_2.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_3.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_4.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT.gif",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SÍSIFO",
        src: "src/img/WEB/ESCARABAJO.jpg",
        alt: "SÍSIFO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA1.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA3.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS_2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "HORCHATA DE CHUFA",
        src: "src/img/WEB/BLANCO/BLANCO_B1.jpg",
        alt: "HORCHATA-DE-CHUFA",
        filts: "PACKAGING | LETTERING | BLANCO",
      },
      {
        name: "HORCHATA DE CHUFA",
        src: "src/img/WEB/BLANCO/GELBLANCO.jpg",
        alt: "HORCHATA-DE-CHUFA",
        filts: "PACKAGING | LETTERING | BLANCO",
      },
      {
        name: "SCATTERGORIES",
        src: "src/img/WEB/PULPO.jpg",
        alt: "SCATTERGORIES",
        filts: "ILUSTRACIÓN",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA.gif",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO3.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO5.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_NAVE.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "CARAMELOS THE BASILISCO",
        src: "src/img/WEB/BASILISCO4.jpg",
        alt: "CARAMELOS-THE-BASILISCO",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "HULAHOP",
        src: "src/img/WEB/HULAHOP/hulalop1.gif",
        alt: "HULAHOP",
        filts: "ILUSTRACIÓN",
      },
      {
        name: "CHOCOLATE EXPRES",
        src: "src/img/WEB/EXPRES.jpg",
        alt: "CHOCOLATE-EXPRES",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "CHERNOBYL",
        src: "src/img/WEB/CHERNOBYL_02.jpg",
        alt: "CHERNOBYL",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "VACAS BEHIAK",
        src: "src/img/WEB/VACAS/ROCK&COWS.gif",
        alt: "VACAS-BEHIAK",
        filts: "ILUSTRACIÓN",
      },
      {
        name: "LEOGATO",
        src: "src/img/WEB/LEOGATO/LEOGATO1.jpg",
        alt: "LEOGATO",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SIN JUEGO NO HAY ARTE",
        src: "src/img/WEB/ARTELANA/ARTELANA.gif",
        alt: "SIN-JUEGO-NO-HAY-ARTE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SIN JUEGO NO HAY ARTE",
        src: "src/img/WEB/ARTELANA/ARTELANA2.jpg",
        alt: "SIN-JUEGO-NO-HAY-ARTE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/PLANCHA.gif",
        alt: "EN-MI-CABEZA-TODO-TIENE-SENTIDO",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_1.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_2.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_3.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_4.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "FRED",
        src: "src/img/WEB/FRED.jpg",
        alt: "FRED",
        filts: "ILUSTRACIÓN",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA1.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA2.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA3.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA4.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA5.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA6.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA7.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA8.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
    ],
  },
  {
    category: "ilustración",
    images: [
      {
        name: "GARGHOLA",
        src: "src/img/WEB/GARGHOLA/GARGHOLA.jpg",
        alt: "GARGHOLA",
        filts: "PACKAGING | LETTERING | ILUSTRACIÓN",
      },
      {
        name: "MOTO",
        src: "src/img/WEB/MOTO/MOTO_1.jpg",
        alt: "MOTO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "MOTO",
        src: "src/img/WEB/MOTO/MOTO_2.jpg",
        alt: "MOTO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "UBICACIÓN",
        src: "src/img/WEB/UBICACION/UBICACION.jpg",
        alt: "UBICACIÓN",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_1..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_2..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_3..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_4..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_5..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "SÍSIFO",
        src: "src/img/WEB/ESCARABAJO.jpg",
        alt: "SÍSIFO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "SCATTERGORIES",
        src: "src/img/WEB/PULPO.jpg",
        alt: "SCATTERGORIES",
        filts: "ILUSTRACIÓN",
      },
      {
        name: "HULAHOP",
        src: "src/img/WEB/HULAHOP/hulalop1.gif",
        alt: "HULAHOP",
        filts: "ILUSTRACIÓN",
      },
      {
        name: "CHERNOBYL",
        src: "src/img/WEB/CHERNOBYL_02.jpg",
        alt: "CHERNOBYL",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "VACAS BEHIAK",
        src: "src/img/WEB/VACAS/ROCK&COWS.gif",
        alt: "VACAS-BEHIAK",
        filts: "ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/PLANCHA.gif",
        alt: "EN-MI-CABEZA-TODO-TIENE-SENTIDO",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_1.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_2.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_3.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_4.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "FRED",
        src: "src/img/WEB/FRED.jpg",
        alt: "FRED",
        filts: "ILUSTRACIÓN",
      },
    ],
  },
  {
    category: "viñetas",
    images: [
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE1.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE2.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MOTO",
        src: "src/img/WEB/MOTO/MOTO_1.jpg",
        alt: "MOTO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "MOTO",
        src: "src/img/WEB/MOTO/MOTO_2.jpg",
        alt: "MOTO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "UBICACIÓN",
        src: "src/img/WEB/UBICACION/UBICACION.jpg",
        alt: "UBICACIÓN",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_1..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_2..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_3..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_4..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_5..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_1.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_2.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_3.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_4.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT.gif",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SÍSIFO",
        src: "src/img/WEB/ESCARABAJO.jpg",
        alt: "SÍSIFO",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA1.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA3.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS_2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA.gif",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO3.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO5.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_NAVE.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "CHERNOBYL",
        src: "src/img/WEB/CHERNOBYL_02.jpg",
        alt: "CHERNOBYL",
        filts: "VIÑETAS | ILUSTRACIÓN",
      },
      {
        name: "LEOGATO",
        src: "src/img/WEB/LEOGATO/LEOGATO1.jpg",
        alt: "LEOGATO",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SIN JUEGO NO HAY ARTE",
        src: "src/img/WEB/ARTELANA/ARTELANA.gif",
        alt: "SIN-JUEGO-NO-HAY-ARTE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SIN JUEGO NO HAY ARTE",
        src: "src/img/WEB/ARTELANA/ARTELANA2.jpg",
        alt: "SIN-JUEGO-NO-HAY-ARTE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA1.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA2.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA3.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA4.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA5.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA6.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA7.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA8.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
    ],
  },
  {
    category: "packaging",
    images: [
      {
        name: "GARGHOLA",
        src: "src/img/WEB/GARGHOLA/GARGHOLA.jpg",
        alt: "GARGHOLA",
        filts: "PACKAGING | LETTERING | ILUSTRACIÓN",
      },
      {
        name: "VINAGRE DE LA ALMUDENA",
        src: "src/img/WEB/ALMUDENA.jpg",
        alt: "VINAGRE-DE-LA-ALMUDENA",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "HORCHATA DE CHUFA",
        src: "src/img/WEB/BLANCO/BLANCO_B1.jpg",
        alt: "HORCHATA-DE-CHUFA",
        filts: "PACKAGING | LETTERING | BLANCO",
      },
      {
        name: "HORCHATA DE CHUFA",
        src: "src/img/WEB/BLANCO/GELBLANCO.jpg",
        alt: "HORCHATA-DE-CHUFA",
        filts: "PACKAGING | LETTERING | BLANCO",
      },
      {
        name: "CARAMELOS THE BASILISCO",
        src: "src/img/WEB/BASILISCO4.jpg",
        alt: "CARAMELOS-THE-BASILISCO",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "CHOCOLATE EXPRES",
        src: "src/img/WEB/EXPRES.jpg",
        alt: "CHOCOLATE-EXPRES",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
    ],
  },
  {
    category: "enfinamientos",
    images: [],
  },
  {
    category: "candelabros",
    images: [
      {
        name: "VINAGRE DE LA ALMUDENA",
        src: "src/img/WEB/ALMUDENA.jpg",
        alt: "VINAGRE-DE-LA-ALMUDENA",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "CARAMELOS THE BASILISCO",
        src: "src/img/WEB/BASILISCO4.jpg",
        alt: "CARAMELOS-THE-BASILISCO",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "CHOCOLATE EXPRES",
        src: "src/img/WEB/EXPRES.jpg",
        alt: "CHOCOLATE-EXPRES",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
    ],
  },
  {
    category: "lapiceando",
    images: [
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/PLANCHA.gif",
        alt: "EN-MI-CABEZA-TODO-TIENE-SENTIDO",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_1.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_2.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_3.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
      {
        name: "EN MI CABEZA TODO TIENE SENTIDO",
        src: "src/img/WEB/PLANCHA/BARCA_4.jpg",
        alt: "BARCA",
        filts: "LAPICEANDO | ILUSTRACIÓN",
      },
    ],
  },
  {
    category: "blancos",
    images: [],
  },
  {
    category: "catpower",
    images: [
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE1.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE2.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "VER LA TELE",
        src: "src/img/WEB/TELE/TELE.gif",
        alt: "VER-LA-TELE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_1.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_2.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_3.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT_4.jpg",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "ZONA DE CONFORT",
        src: "src/img/WEB/CONFORT/CONFORT.gif",
        alt: "ZONA-DE-CONFORT",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA1.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA3.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS_2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/CAJA.gif",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO3.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO5.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO1.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_ESPACIO.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "UN GATO, UNA CAJA",
        src: "src/img/WEB/GATO_CAJA/GATO_NAVE.jpg",
        alt: "UN-GATO-UNA-CAJA",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "LEOGATO",
        src: "src/img/WEB/LEOGATO/LEOGATO1.jpg",
        alt: "LEOGATO",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SIN JUEGO NO HAY ARTE",
        src: "src/img/WEB/ARTELANA/ARTELANA.gif",
        alt: "SIN-JUEGO-NO-HAY-ARTE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "SIN JUEGO NO HAY ARTE",
        src: "src/img/WEB/ARTELANA/ARTELANA2.jpg",
        alt: "SIN-JUEGO-NO-HAY-ARTE",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA1.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA2.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA3.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA4.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA5.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA6.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA7.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
      {
        name: "MENTE SUPERIOR",
        src: "src/img/WEB/GATO_PECES/PECERA8.jpg",
        alt: "MENTE-SUPERIOR",
        filts: "VIÑETAS | CATPOWER",
      },
    ],
  },
  {
    category: "lettering",
    images: [
      {
        name: "GARGHOLA",
        src: "src/img/WEB/GARGHOLA/GARGHOLA.jpg",
        alt: "GARGHOLA",
        filts: "PACKAGING | LETTERING | ILUSTRACIÓN",
      },
      {
        name: "VINAGRE DE LA ALMUDENA",
        src: "src/img/WEB/ALMUDENA.jpg",
        alt: "VINAGRE-DE-LA-ALMUDENA",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "HORCHATA DE CHUFA",
        src: "src/img/WEB/BLANCO/BLANCO_B1.jpg",
        alt: "HORCHATA-DE-CHUFA",
        filts: "PACKAGING | LETTERING | BLANCO",
      },
      {
        name: "HORCHATA DE CHUFA",
        src: "src/img/WEB/BLANCO/GELBLANCO.jpg",
        alt: "HORCHATA-DE-CHUFA",
        filts: "PACKAGING | LETTERING | BLANCO",
      },
      {
        name: "CARAMELOS THE BASILISCO",
        src: "src/img/WEB/BASILISCO4.jpg",
        alt: "CARAMELOS-THE-BASILISCO",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
      {
        name: "CHOCOLATE EXPRES",
        src: "src/img/WEB/EXPRES.jpg",
        alt: "CHOCOLATE-EXPRES",
        filts: "PACKAGING | LETTERING | CANDELABROS",
      },
    ],
  },
  {
    category: "desconciertos",
    images: [
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_1..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_2..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_3..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_4..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "PERIÓDICO",
        src: "src/img/WEB/PERIODICO/periodico_5..jpg",
        alt: "PERIÓDICO",
        filts: "ILUSTRACIÓN | VIÑETAS | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA1.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA3.gif",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS_2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLA2.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
      {
        name: "SIESTA",
        src: "src/img/WEB/ESPACIO/ESTRELLAS.jpg",
        alt: "SIESTA",
        filts: "VIÑETAS | CATPOWER | DESCONCIERTOS",
      },
    ],
  },
];
